export const ORGANIZATION_MANAGER_LIMIT = 20;
export const ORGANIZATION_LINK_LIMIT = 20;
export const ORGANIZATION_FEATURED_RESOURCE_LIMIT = 20;

export const ORGANIZATION_MANAGER_READ_LIMIT = ORGANIZATION_MANAGER_LIMIT + 1;
export const ORGANIZATION_LINK_READ_LIMIT = ORGANIZATION_LINK_LIMIT + 1;
export const ORGANIZATION_FEATURED_RESOURCE_READ_LIMIT =
  ORGANIZATION_FEATURED_RESOURCE_LIMIT + 1;
